FROM c33s/debian:latest

MAINTAINER c33s

ENV DOCKER_PHP_VERSION 7.0
ENV COMPOSER_ALLOW_SUPERUSER true
ENV COMPOSER_DISABLE_XDEBUG_WARN true
ENV DOCKER_VERSION_COMPOSER 1.6.2
ENV DOCKER_VERSION_COMPOSER_PRESTISSIMO ^0.3
ENV DOCKER_VERSION_COMPOSER_ASSET_PLUGIN ~1.3
ENV DOCKER_VERSION_ROBO 1.2.1

ARG DEBIAN_FRONTEND=noninteractive

COPY bin/provision-base_7.x.sh /root/provision-base.sh
RUN chmod +x /root/provision-base.sh; sync; /root/provision-base.sh

COPY bin/provision-${DOCKER_PHP_VERSION}.sh /root/provision-${DOCKER_PHP_VERSION}.sh
RUN chmod +x /root/provision-${DOCKER_PHP_VERSION}.sh; sync; /root/provision-${DOCKER_PHP_VERSION}.sh; php -v

CMD ["php", "-a"]







