FROM c33s/debian:jessie

MAINTAINER c33s

ENV DOCKER_PHP_VERSION 5.6
ARG DEBIAN_FRONTEND=noninteractive

# does not use base-provision.sh
#COPY bin/provision-base.sh /root/provision-base.sh
#RUN chmod +x /root/provision-base.sh && /root/provision-base.sh

COPY bin/provision-${DOCKER_PHP_VERSION}.sh /root/provision-${DOCKER_PHP_VERSION}.sh
RUN chmod +x /root/provision-${DOCKER_PHP_VERSION}.sh && /root/provision-${DOCKER_PHP_VERSION}.sh && php -v

CMD ["php", "-a"]







