image: docker:20.10.6 #20.10.6, 20.10, 20, latest

stages:
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:20.10.6-dind #20.10.6-dind, 20.10-dind, 20-dind, dind

## Debian Tests
test_matrix_debian:
  stage: test
  parallel:
    matrix:
      - DEBIAN_VERSION: [buster, stretch, jessie]
#      - DEBIAN_VERSION: [ buster, stretch, jessie, wheezy]
  script:
    - ./tests/debian/debian_${DEBIAN_VERSION}_test.sh
#  only:
#    changes:
#      - debian/**/*

## Php Tests
test_matrix_php:
  stage: test
  parallel:
    matrix:
      - PHP_VERSION:     ['8.0', '7.4', '7.3', '7.2', '7.1']
  script:
    - ./tests/php/php_${PHP_VERSION}_test.sh
#  only:
#    changes:
#      - php/**/*

## Build Tests
test_matrix_build:
  stage: test
  parallel:
    matrix:
      - DEBIAN_VERSION: [ buster, stretch]
  script:
    - ./tests/build/build_${DEBIAN_VERSION}_test.sh
#  only:
#    changes:
#      - build/**/*
