stages:
  - build
#  - test
#  - deploy

.base_build:
  stage: build
  script:
    - cd debian && docker build --file Dockerfile-buster .

build_buster_10:
  extends: .base_build
  image: docker:latest
