# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "c33s/debian-64-stretch"
  
  config.vm.usable_port_range = (2222..2250)
  config.vm.hostname = "vagrant.local"
  
  ##################################################################################################
  # Plugin https://github.com/oscar-stack/vagrant-hosts
  ##################################################################################################
  if Vagrant.has_plugin?("vagrant-hosts")
    config.vm.provision :hosts, :sync_hosts => true
  end
  
  ##################################################################################################
  # Plugin https://github.com/tmatilai/vagrant-proxyconf
  ##################################################################################################
  if Vagrant.has_plugin?("vagrant-proxyconf")
    if ENV.has_key?('http_proxy')
      config.proxy.http     = "#{ENV['http_proxy']}"
    end
    if ENV.has_key?('https_proxy')
      config.proxy.https    = "#{ENV['https_proxy']}"
    end
    config.proxy.no_proxy = "localhost,127.0.0.1,127.0.0.0/8,127.0.1.1,.example.com,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12"
  end
   
  ##################################################################################################
  # Plugin http://fgrehm.viewdocs.io/vagrant-cachier/
  ##################################################################################################
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.auto_detect = false
    config.cache.enable :apt
  end

  config.vm.provision :shell, :name => "Fixing TTY", :keep_color => true, :privileged => true, :inline => <<-SHELL
      (grep -q -E '^mesg n$' /root/.profile && sed -i 's/^mesg n$/tty -s \\&\\& mesg n/g' /root/.profile && echo 'Ignore the previous error about stdin not being a tty. Fixing it now...') || exit 0;
  SHELL

  config.vm.provision "shell", :keep_color => true, path: "provision.sh"
end
